name: Compile and Deploy PDF

on:
  push:
    paths:
      - '**/*.tex' # Trigger on changes to any .tex files

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install minimal LaTeX environment with latexmk
        run: |
          sudo apt update
          sudo apt install -y texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended latexmk


      - name: Compile all LaTeX files
        run: |
          mkdir -p output
          latexmk -pdf -outdir=output resume.tex
          latexmk -pdf -outdir=output cv.tex

          cat output/resume.log || true
          cat output/cv.log || true

      - name: Clean auxiliary files
        run: |
          latexmk -c
          rm -f output/*.{aux,log,out,toc,fls,fdb_latexmk}

      # - name: Move PDFs to output directory
      #   run: |
      #     mkdir -p output
      #     mv *.pdf output/

      - name: Deploy PDFs to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: output
          force_orphan: true